# Site settings
title: 전수열 블로그
email: devxoul@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Suyeol Jeon's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.xoul.kr" # the base hostname & protocol for your site
facebook_username: devxoul
github_username:  devxoul

# Build settings
markdown: redcarpet
highlighter: pygments
